title: PWeb 2021 &#124; Farhan Arifandi
theme: jekyll-theme-minimal

author: Farhan Arifandi

# Site Author
author:
  name             : "Farhan Arifandi"
  location         : "Denpasar, Bali"
  email            : "farhanarifandi@yahoo.com"
  facebook         : "farfnd"
  github           : "farfnd"
  instagram        : "frhnar"
  linkedin         : "farfnd"
