theme: jekyll-theme-minimal
title: PWeb 2021 | Farhan Arifandi
author: Farhan Arifandi

social-network-links:
  email: "farhanarifandi@yahoo.com"
  facebook: farfnd
  github: farfnd
  instagram: frhnar
