title: PWeb 2021 &#124; Farhan Arifandi
theme: jekyll-theme-minimal

author: Farhan Arifandi

social-network-links:
  email: "farhanarifandi@yahoo.com"
  facebook: farfnd
  github: farfnd
  instagram: frhnar
