theme: jekyll-theme-minimal
title: PWeb 2021
author: Farhan Arifandi
title_separator          : "|"
description              : Repository tugas mata kuliah Pemrograman Web (IF184504) tahun 2021.

social-network-links:
  email: "farhanarifandi@yahoo.com"
  facebook: farfnd
  github: farfnd
  instagram: frhnar
